config/routes.rb
Rails.application.routes.draw do

	namespace :api, defaults: {format: 'json'} do

		namespace :v1 do
			resources :feeds do
			member do
				post 'like_count'
			end
		end   
		resources :comments, only:[:index, :create] 

		end
	end	

		resources :feeds do
			member do
				post 'like_count'
			end
			resources :comments, only:[:index, :create]

		end
		
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :feed
    validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

end

app/models/feed.rb
class Feed < ApplicationRecord
	require 'json'
	require 'open-uri'

	has_many :comments

	
	def self.save_data

		feeds = JSON.load(open('https://www.teleton.cl/feed/?json'))
			data = feeds["items"]
			data.each do |dat|
				row = Feed.new(
					:fecha => dat["fecha"],
					:content => dat["content"],
					:all_content => dat["all_content"],
					:image => dat["image"],
					:link => dat["link"],
					:title => dat["title"],
					:categories => dat["categories"],
					:comments  => dat["comments"],
					:like => dat["like"].to_i
					)
				row.save 
			end
	end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController


  def index
  	@comments = Comment.find_by(params)
  	render json: @comment
  end

	def create
			if params[:name].present? && params[:email].present?
  	comment = Comment.new
  	comment.name = params[:name]
  	comment.email = params[:email]
  	comment.comment = params[:comment]
  	comment.feed_id = params[:feed_id]
  	comment.save
  else 
  	comment = Comment.new
  	comment.name = "Anónimo"
  	comment.email = "Sin email"
  	comment.comment = params[:comment]
  	comment.feed_id = params[:feed_id]
  	comment.save
    end
		render json: @comment, notice: "Anómimo" 
	end



end

app/controllers/api/v1/feeds_controller.rb
class Api::V1::FeedsController < ApplicationController
	before_action :set_feed, only: [:show]


	def index
		@feeds = Feed.all
		render json: @feeds
	end

	def show
		render json: @feed
	end

	def like_count

		@feed.like += 1
		@feed.save
		redirect_to feed_path(@feed), notice: "Like succsess"
		
	end

	private
	    # Use callbacks to share common setup or constraints between actions.
	    def set_feed
	    	@feed = Feed.find(params[:id])
	    end

	  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	if params[:name].present? && params[:email].present?
  	comment = Comment.new
  	comment.name = params[:name]
  	comment.email = params[:email]
  	comment.comment = params[:comment]
  	comment.feed_id = params[:feed_id]
  	comment.save
  else 
  	comment = Comment.new
  	comment.name = "Anónimo"
  	comment.email = "anonimo@anonimo.cl"
  	comment.comment = params[:comment]
  	comment.feed_id = params[:feed_id]
  	comment.save
    end

    redirect_to feed_path(params[:feed_id]), notice: 'Comentario Agregado'
  end

  def index
    
  end


end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
	before_action :set_feed, only: [:show, :like_count]
  
  def index
  	@feeds = Feed.all
  end

	def show
		@comments = Comment.where(feed_id: params[:id])

	end

	def like_count

    @feed.like += 1
    @feed.save
    redirect_to feed_path(@feed), notice: "Like succsess"
     

	end

	private
	    # Use callbacks to share common setup or constraints between actions.
	    def set_feed
	      @feed = Feed.find(params[:id])
	    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/index.html.erb
<div class="container">
<%= image_tag 'logo.png' %>
<div class="row">
<% @feeds.each do |feed| %>
	<div class="col-md-8 col-md-offset-3 ">
		<p><%= feed.fecha %></p>
		<h1 class="jumbotron"><%= feed.title %></h1>
		<p><%= feed.all_content.html_safe %></p>
		<%= link_to 'Ver mas', feed, class:"btn btn-primary"  %>
		</div>
<% end %>
	</div>
</div>

app/views/feeds/show.html.erb
<div class="container">
	<%= image_tag 'logo.png' %>
	<div class="row">
		<div class="col-md-8 col-md-offset-3 ">
			<p><%= @feed.fecha %></p>
			<h1 class="jumbotron"><%= @feed.title %></h1>
			<p><%= @feed.all_content.html_safe %></p>
			<%= link_to "Me gusta", like_count_feed_path(@feed), method: :post %> | <%= @feed.like %>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-8 col-md-offset-3 ">
			<h2>commentarios</h2>

			<% if @comments.blank? %>

			<p>No hay comentarios!</p>

			<% else %>
				<table class="table table-hover">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Correo</th>
						<th>Comentario</th>
					</tr>
				</thead>
				<tbody>
			<% @comments.each do |comment| %>
					<tr>
					<td><%= comment.name %></td>
					<td><%= comment.email %></td>
					<td><%= comment.comment %></td>
					</tr>
			<% end %>
				</tbody>
				
			</table>

			<% end %>
		</div>
	</div>
	<div class="row">
		<%= render "shared/form", feed: params[:id] %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeletonApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
		

		<%= favicon_link_tag '140x80' %>
      
    <%= csrf_meta_tags %>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/readable/bootstrap.min.css" rel="stylesheet" integrity="sha384-Li5uVfY2bSkD3WQyiHX8tJd0aMF91rMrQP5aAewFkHkVSTT2TmD2PehZeMmm7aiL" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-3 ">

			<%= form_tag feed_comments_path(feed), method: :post do %>
			
			<div class="form-group">
				<div class="field">
					<%= label_tag 'Nombre' %>
					<%= text_field_tag 'name', nil, class:"form-control"  %>
				</div>
			</div>
			<div class="form-group">
				<div class="field">
					<%= label_tag 'Correo' %>
					<%= email_field_tag 'email', nil, class:"form-control" %>
				</div>
			</div>
			<div class="form-group">
				<div class="field">
					<%= label_tag "Comentario" %>
					<%= text_area_tag 'comment', nil,  class:"form-control", :placeholder => "comenta"  %>
					<br>
					<%= submit_tag 'Enviar', class:"btn btn-success" %>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>